name: Linting
on:
  pull_request:
  push:
    branches:
      - "spell-testing"

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup ReviewDog
        uses: reviewdog/action-setup@v1.0.6
      - name: Run misspell with reviewdog
        uses: reviewdog/action-misspell@v1.14.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: "github-pr-review"
          level: warning
          locale: "US"
          path: |
            input
            src
  languagetool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup ReviewDog
        uses: reviewdog/action-setup@v1.0.6
      - name: Run LanguageTool with reviewdog
        uses: AdmiringWorm/action-languagetool@long-text-fix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: "github-check"
          level: warning
          language: en-US
          base_ref: master
