name: Linting
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup ReviewDog
        uses: reviewdog/action-setup@v1.0.6
      - name: Run misspell with reviewdog
        uses: reviewdog/action-misspell@v1.14.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: "github-pr-review"
          level: warning
          locale: "US"
          path: |
            input
            src
  languagetool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup ReviewDog
        uses: reviewdog/action-setup@v1.0.6
      - name: Run LanguageTool with reviewdog
        uses: reviewdog/action-languagetool@v1.12.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: "github-pr-review"
          level: warning
          language: en-US
