name: Linting
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10 # We only fetch the last 10 commits. This should generally be enough to get the master branch
      - name: Setup ReviewDog
        uses: reviewdog/action-setup@v1.0.6
      - name: Run misspell with reviewdog
        uses: reviewdog/action-misspell@v1.14.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: "github-pr-review"
          level: warning
          locale: "US"
          path: |
            input
            src
  languagetool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10 # We only fetch the last 10 commits. This should generally be enough to get the master branch
      - name: Setup ReviewDog
        uses: reviewdog/action-setup@v1.0.6
      - name: Run LanguageTool with reviewdog
        uses: AdmiringWorm/action-languagetool@long-text-fix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: "github-pr-review"
          level: warning
          language: en-US
          base_ref: master
