name: Linting
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch master branch
        run: git fetch origin master
      - name: Run misspell with reviewdog
        uses: reviewdog/action-misspell@v1.14.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: "github-pr-review"
          level: warning
          locale: "US"
          path: |
            input
            src
  languagetool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch master branch
        run: git fetch origin master
      - name: Run LanguageTool with reviewdog
        uses: chocolatey/action-languagetool@develop
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: "github-pr-review"
          level: warning
          language: en-US
          base_ref: master
